micronaut:
  application:
    name: enumtest
datasources:
  default:
    url: jdbc:postgresql://postgres:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE
    dialect: postgres

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages:
      - at.bayava.entity